name: ESLint

on:
    workflow_call:

permissions:
    contents: write
    packages: read

jobs:
    lint:
        name: Create Pull Request with ESLint Changes
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              with:
                token: ${{ secrets.BOT_TOKEN }}
                ref: ${{ github.head_ref }}
            - name: Setup PNPM
              uses: pnpm/action-setup@v6
              with:
                version: 11.3.0
            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                node-version: 24.16.0
                registry-url: https://npm.pkg.github.com/
                cache: pnpm
            - name: Lint Code
              run: pnpm dlx @use-nyte/eslint-config@latest
            - name: Commit Changes
              uses: stefanzweifel/git-auto-commit-action@v7.1.0
              with:
                push_options: "--force-with-lease --force-if-includes"
                commit_message: |
                  chore: lint code
                  

                  skip-checks: true
                commit_user_name: "use-nyte-bot"
                commit_user_email: ${{ secrets.BOT_EMAIL }}
                commit_author: "use-nyte-bot <${{ secrets.BOT_EMAIL }}>"
