name: Release Node.js Package

on:
  workflow_call:

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Release Node.js Package
    runs-on: ubuntu-latest
    steps:
      - name: Create Release PR
        uses: googleapis/release-please-action@v5.0.0
        id: release
        with:
          token: ${{ secrets.BOT_TOKEN }}
          release-type: node
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ github.head_ref }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11.3.0
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.16.0
          registry-url: https://npm.pkg.github.com/
          cache: pnpm
        if: ${{ steps.release.outputs.release_created }}
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish Package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
